const compliments = [
    "You're amazing just the way you are!",
    "You have a great sense of humor!",
    "You're incredibly thoughtful and kind.",
    "You are more powerful than you know.",
    "You light up the room!",
    "You're a true friend.",
    "You inspire me!",
    "Your creativity knows no bounds!",
    "You have a heart of gold.",
    "You make a difference in the world.",
    "Your positivity is contagious!",
    "You have an incredible work ethic.",
    "You bring out the best in people.",
    "Your smile brightens everyone's day.",
    "You're so talented in everything you do.",
    "Your kindness makes the world a better place.",
    "You have a unique and wonderful perspective.",
    "Your enthusiasm is truly inspiring!",
    "You are capable of achieving great things.",
    "You always know how to make someone feel special.",
    "Your confidence is admirable.",
    "You have a beautiful soul.",
    "Your generosity knows no limits.",
    "You have a great eye for detail.",
    "Your passion is truly motivating!",
    "You are an amazing listener.",
    "You're stronger than you think!",
    "Your laughter is infectious.",
    "You have a natural gift for making others feel valued.",
    "You make the world a better place just by being in it.",
    "You have impeccable taste and style!",
    "Your intelligence shines through in every conversation.",
    "You handle challenges with grace and wisdom.",
    "Your energy is magnetic and uplifting.",
    "You're a natural-born leader.",
    "Your compassion touches everyone around you.",
    "You have a remarkable ability to solve problems.",
    "Your presence makes any situation better.",
    "You're incredibly resilient and strong.",
    "Your optimism is a beacon of hope.",
    "You have a wonderful way with words.",
    "Your dedication to excellence is impressive.",
    "You make complex things seem simple.",
    "Your authenticity is refreshing and rare.",
    "You have a gift for making people feel heard.",
    "Your courage in facing adversity is inspiring.",
    "You're a constant source of wisdom and guidance.",
    "Your patience and understanding are remarkable.",
    "You have an extraordinary ability to connect with others.",
    "Your vision for the future is inspiring.",
    "You're incredibly resourceful and innovative.",
    "Your emotional intelligence is exceptional.",
    "You have a talent for bringing people together.",
    "Your commitment to growth is admirable.",
    "You make learning fun and exciting.",
    "Your intuition is almost always right.",
    "You have a calming presence that soothes others.",
    "Your attention to detail is extraordinary.",
    "You're a master at turning ideas into reality.",
    "Your sense of adventure is exhilarating.",
    "You have a rare combination of strength and gentleness.",
    "Your ability to adapt to change is remarkable.",
    "You're a wonderful mentor and teacher.",
    "Your generosity extends beyond material things.",
    "You have a photographic memory for what matters.",
    "Your determination is unstoppable.",
    "You make everyone around you feel important.",
    "Your artistic talents are breathtaking.",
    "You have a strategic mind that sees opportunities everywhere.",
    "Your loyalty is unwavering and precious.",
    "You're a brilliant problem-solver.",
    "Your voice is soothing and comforting.",
    "You have an incredible memory for details.",
    "Your work ethic sets a standard for excellence.",
    "You're exceptionally good at reading people.",
    "Your cooking skills are restaurant-quality!",
    "You have a natural talent for photography.",
    "Your musical abilities are extraordinary.",
    "You're a gifted writer with a unique voice.",
    "Your dance moves are absolutely captivating.",
    "You have a green thumb that brings life everywhere.",
    "Your fashion sense is always on point.",
    "You're an incredible public speaker.",
    "Your athletic abilities are impressive.",
    "You have a way with animals that's magical.",
    "Your tech skills are cutting-edge.",
    "You're a financial wizard with money matters.",
    "Your gardening skills create paradise.",
    "You have a voice that could be on radio.",
    "Your parenting skills are exemplary.",
    "You're a natural at making people comfortable.",
    "Your baking could win awards!",
    "You have a talent for interior design.",
    "Your car maintenance skills are impressive.",
    "You're a whiz at fixing things around the house.",
    "Your knowledge of history is encyclopedic.",
    "You have a way with children that's beautiful.",
    "Your first aid skills could save lives.",
    "You're a navigation expert who never gets lost.",
    "Your memory for names and faces is incredible.",
    "You have a talent for learning languages.",
    "Your negotiation skills are masterful.",
    "You're a spreadsheet genius!",
    "Your event planning abilities are flawless.",
    "You have a gift for seeing the big picture.",
    "Your time management is incredibly efficient.",
    "You're a natural at conflict resolution.",
    "Your research skills are thorough and precise.",
    "You have a way of simplifying complex concepts.",
    "Your networking abilities are exceptional.",
    "You're a coding wizard!",
    "Your analytical thinking is razor-sharp.",
    "You have a talent for building community.",
    "Your mentorship has changed lives.",
    "You're a beacon of integrity and honesty.",
    "Your emotional support means the world to others.",
    "You have a gift for celebrating others' successes.",
    "Your ability to forgive is truly remarkable.",
    "You're a pillar of strength in difficult times.",
    "Your wisdom beyond your years is astounding.",
    "You have a way of making dreams come true.",
    "Your friendship is a precious gift.",
    "You're exactly what someone needed today.",
    "Your existence makes the universe better.",
    "You have the power to heal with your presence.",
    "Your light shines brighter than you realize.",
    "You're a masterpiece in human form.",
    "Your potential is limitless and extraordinary.",
    "You have everything you need within you.",
    "Your journey inspires everyone who knows you.",
    "You're writing a beautiful story with your life.",
    "Your impact on this world is significant.",
    "You have the courage to be authentically you.",
    "Your spirit is unbreakable and magnificent.",
    "You're a gift to everyone who knows you.",
    "Your future is brighter than you can imagine.",
    "You have the strength to overcome any obstacle.",
    "Your heart is your superpower.",
    "You're making progress even when it doesn't feel like it.",
    "Your small actions create big changes.",
    "You have the wisdom to know what truly matters.",
    "Your presence is a present to the world.",
    "You're enough exactly as you are in this moment.",
    "Your uniqueness is your greatest strength.",
    "You have the power to create your own happiness.",
    "Your resilience in facing challenges is heroic.",
    "You're growing in beautiful ways every day.",
    "Your compassion makes you truly beautiful.",
    "You have the ability to turn pain into purpose.",
    "Your journey is valid and important.",
    "You're worthy of all the love you receive.",
    "Your existence matters more than you know.",
    "You have the capacity for infinite love.",
    "Your potential for greatness is undeniable.",
    "You're creating ripples of positive change.",
    "Your authentic self is your best self.",
    "You have the vision to see what others miss.",
    "Your energy creates miracles every day.",
    "You're exactly where you need to be right now.",
    "Your growth inspires others to grow too.",
    "You have the power to rewrite your story.",
    "Your courage to be vulnerable is beautiful.",
    "You're a catalyst for positive transformation.",
    "Your ability to love is your greatest gift.",
    "You have everything required for your journey.",
    "Your presence makes difficult times bearable.",
    "You're a source of hope and inspiration.",
    "Your capacity for joy is boundless.",
    "You have the wisdom to learn from every experience.",
    "Your spirit cannot be broken by circumstances.",
    "You're a living example of resilience.",
    "Your heart knows the way even when you're lost.",
    "You have the strength to carry others when needed.",
    "Your light cannot be dimmed by darkness.",
    "You're a testament to human potential.",
    "Your journey is making you stronger every day.",
    "You have the power to choose your response.",
    "Your existence makes the world more beautiful.",
    "You're capable of weathering any storm.",
    "Your ability to start over is courageous.",
    "You have the insight to see your own worth.",
    "Your determination will take you far.",
    "You're building a life filled with meaning.",
    "Your capacity for growth is unlimited.",
    "You have the wisdom to appreciate small moments.",
    "Your spirit shines through your eyes.",
    "You're learning valuable lessons every day.",
    "Your heart is wiser than you realize.",
    "You have the strength to be gentle.",
    "Your presence is calming and reassuring.",
    "You're exactly what this world needs.",
    "Your ability to find joy is remarkable.",
    "You have the courage to dream big dreams.",
    "Your resilience is your superpower.",
    "You're becoming who you're meant to be.",
    "Your journey is uniquely yours and beautiful.",
    "You have the power to inspire change.",
    "Your authenticity attracts the right people.",
    "You're a work in progress and that's perfect.",
    "Your capacity for love knows no bounds.",
    "You have everything within you to succeed.",
    "Your presence makes ordinary moments special.",
    "You're writing your story one day at a time.",
    "Your ability to hope is revolutionary.",
    "You have the strength to be vulnerable.",
    "Your spirit cannot be contained.",
    "You're exactly enough in this moment.",
    "Your potential unfolds in perfect timing.",
    "You have the wisdom to trust the process.",
    "Your heart leads you to where you need to be.",
    "You're creating your reality with each thought.",
    "Your ability to persevere is admirable.",
    "You have the courage to be different.",
    "Your uniqueness is your magic.",
    "You're a beautiful soul having a human experience.",
    "Your capacity for forgiveness is healing.",
    "You have the power to transform pain.",
    "Your journey is teaching you exactly what you need.",
    "You're exactly where you're supposed to be.",
    "Your ability to love yourself is growing.",
    "You have the strength to set boundaries.",
    "Your intuition is your inner compass.",
    "You're becoming more you every day.",
    "Your presence is a blessing to others.",
    "You have the wisdom to know when to rest.",
    "Your ability to adapt is your strength.",
    "You're learning to trust yourself more.",
    "Your heart knows what your mind cannot see.",
    "You have the courage to follow your heart.",
    "Your authenticity is your greatest asset.",
    "You're exactly who you need to be right now.",
    "Your potential is unfolding beautifully.",
    "You have everything you need within you.",
    "Your journey is preparing you for greatness.",
    "You're stronger than your struggles.",
    "Your ability to find light in darkness is amazing.",
    "You have the power to create your happiness.",
    "Your spirit cannot be defeated.",
    "You're exactly perfect in your imperfection.",
    "Your capacity for growth is inspiring.",
    "You have the wisdom to appreciate the journey.",
    "Your presence makes everything better.",
    "You're learning valuable lessons every day.",
    "Your heart is your guiding light.",
    "You have the strength to be authentically you.",
    "Your ability to rise after falling is heroic.",
    "You're becoming the person you admire.",
    "Your journey is making you wiser.",
    "You have the power to choose happiness.",
    "Your spirit shines brighter each day.",
    "You're exactly what someone needs today.",
    "Your potential is limitless.",
    "You have everything required for your path.",
    "Your presence is a gift to this world.",
    "You're growing in ways you can't yet see.",
    "Your ability to love is transforming you.",
    "You have the courage to face your fears.",
    "Your authenticity is changing lives.",
    "You're exactly where you need to grow.",
    "Your capacity for joy is expanding.",
    "You have the wisdom to learn from everything.",
    "Your spirit is unbreakable.",
    "You're creating your beautiful life.",
    "Your ability to hope is powerful.",
    "You have the strength to be patient.",
    "Your journey is uniquely meaningful.",
    "You're exactly enough as you are.",
    "Your potential is being realized daily.",
    "You have everything within you to thrive.",
    "Your presence makes moments memorable.",
    "You're learning to trust the journey.",
    "Your heart knows the truth.",
    "You have the courage to be yourself.",
    "Your authenticity is your power.",
    "You're exactly right for this moment.",
    "Your capacity for love is infinite.",
    "You have the wisdom to see beauty everywhere.",
    "Your spirit cannot be dimmed.",
    "You're becoming who you're meant to be.",
    "Your ability to persevere is remarkable.",
    "You have the strength to keep going.",
    "Your journey is filled with purpose.",
    "You're exactly what the world needs.",
    "Your potential is extraordinary.",
    "You have everything you need to succeed.",
    "Your presence is transformative.",
    "You're growing stronger every day.",
    "Your ability to love deeply is beautiful.",
    "You have the courage to live fully.",
    "Your authenticity inspires others.",
    "You're exactly perfect in this moment.",
    "Your capacity for happiness is vast.",
    "You have the wisdom to appreciate now.",
    "Your spirit is magnificent.",
    "You're creating a life you love.",
    "Your ability to overcome is incredible.",
    "You have the strength to be kind.",
    "Your journey is important.",
    "You're exactly enough.",
    "Your potential is boundless.",
    "You have everything within you.",
    "Your presence matters.",
    "You're growing beautifully.",
    "Your ability to love is enough.",
    "You have the courage to try.",
    "Your authenticity matters.",
    "You're exactly right.",
    "Your capacity is great.",
    "You have the wisdom.",
    "Your spirit is strong."
];

async function complimentCommand(sock, chatId, message) {
    try {
        if (!message || !chatId) {
            console.log('Invalid message or chatId:', { message, chatId });
            return;
        }

        let userToCompliment;
        
        // Check for mentioned users
        if (message.message?.extendedTextMessage?.contextInfo?.mentionedJid?.length > 0) {
            userToCompliment = message.message.extendedTextMessage.contextInfo.mentionedJid[0];
        }
        // Check for replied message
        else if (message.message?.extendedTextMessage?.contextInfo?.participant) {
            userToCompliment = message.message.extendedTextMessage.contextInfo.participant;
        }
        
        if (!userToCompliment) {
            await sock.sendMessage(chatId, { 
                text: 'Please mention someone or reply to their message to compliment them!'
            });
            return;
        }

        const compliment = compliments[Math.floor(Math.random() * compliments.length)];

        // Add delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 1000));

        await sock.sendMessage(chatId, { 
            text: `Hey @${userToCompliment.split('@')[0]}, ${compliment}`,
            mentions: [userToCompliment]
        });
    } catch (error) {
        console.error('Error in compliment command:', error);
        if (error.data === 429) {
            await new Promise(resolve => setTimeout(resolve, 2000));
            try {
                await sock.sendMessage(chatId, { 
                    text: 'Please try again in a few seconds.'
                });
            } catch (retryError) {
                console.error('Error sending retry message:', retryError);
            }
        } else {
            try {
                await sock.sendMessage(chatId, { 
                    text: 'An error occurred while sending the compliment.'
                });
            } catch (sendError) {
                console.error('Error sending error message:', sendError);
            }
        }
    }
}

module.exports = { complimentCommand };
